# Generated by Django 3.2.7 on 2021-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='language',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='contact_me',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact_me',
            name='image',
            field=models.ImageField(null=True, upload_to='contactme'),
        ),
        migrations.AddField(
            model_name='contact_me',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='contact_me',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='contact_me',
            name='resume',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='contact_me',
            name='techno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact_me',
            name='telegram',
            field=models.URLField(null=True),
        ),
    ]
