# Generated by Django 3.2.7 on 2021-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210914_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='dagree',
        ),
        migrations.AddField(
            model_name='experiencetranslation',
            name='dagree',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
